version: '3.1'

services:

        wordpress:
                image: wordpress
                networks:
                        - core-infra
                ports:
                        - 28080:80
                environment:
                        WORDPRESS_DB_PASSWORD: example

        mysql:
                image: mysql:5.7
                networks:
                        - core-infra
                environment:
                        MYSQL_ROOT_PASSWORD: example

networks:
        core-infra:
                external: true
