registry:
        restart: always
        image: registry:2
        ports:
                - 0.0.0.0:5000:5000
        environment:
                DD: 1
                #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
                #REGISTRY_HTTP_TLS_KEY: /certs/domain.key
                #REGISTRY_AUTH: htpasswd
                #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
                #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
                - /opt/data.d/compose/registry/data:/var/lib/registry
                - /opt/data.d/compose/registry/certs:/certs
                - /opt/data.d/compose/registry/auth:/auth
