version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
      - "discovery.type: zen"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - /home/rogera/code/ase-docker/elasticsearch.composer.d/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

    ports:
      - 9200:9200
      - 9300:9200
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
